//go:build go1.22

// Package contract provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package contract

import (
	"context"
	"errors"
	"fmt"
	"net/http"
	"time"

	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	ConsoleSessionScopes consoleSessionContextKey = "consoleSession.Scopes"
	ProjectApiKeyScopes  projectApiKeyContextKey  = "projectApiKey.Scopes"
)

// Defines values for ApiKeyStatus.
const (
	ApiKeyStatusActive  ApiKeyStatus = "active"
	ApiKeyStatusRevoked ApiKeyStatus = "revoked"
)

// Valid indicates whether the value is a known member of the ApiKeyStatus enum.
func (e ApiKeyStatus) Valid() bool {
	switch e {
	case ApiKeyStatusActive:
		return true
	case ApiKeyStatusRevoked:
		return true
	default:
		return false
	}
}

// Defines values for ApiKeySecretStatus.
const (
	ApiKeySecretStatusActive  ApiKeySecretStatus = "active"
	ApiKeySecretStatusRevoked ApiKeySecretStatus = "revoked"
)

// Valid indicates whether the value is a known member of the ApiKeySecretStatus enum.
func (e ApiKeySecretStatus) Valid() bool {
	switch e {
	case ApiKeySecretStatusActive:
		return true
	case ApiKeySecretStatusRevoked:
		return true
	default:
		return false
	}
}

// Defines values for AuditEventActorType.
const (
	AuditEventActorTypeApiKey       AuditEventActorType = "api_key"
	AuditEventActorTypeProjectUser  AuditEventActorType = "project_user"
	AuditEventActorTypeSystem       AuditEventActorType = "system"
	AuditEventActorTypeTenantMember AuditEventActorType = "tenant_member"
)

// Valid indicates whether the value is a known member of the AuditEventActorType enum.
func (e AuditEventActorType) Valid() bool {
	switch e {
	case AuditEventActorTypeApiKey:
		return true
	case AuditEventActorTypeProjectUser:
		return true
	case AuditEventActorTypeSystem:
		return true
	case AuditEventActorTypeTenantMember:
		return true
	default:
		return false
	}
}

// Defines values for CreateProjectRequestEnvironment.
const (
	CreateProjectRequestEnvironmentProduction CreateProjectRequestEnvironment = "production"
	CreateProjectRequestEnvironmentSandbox    CreateProjectRequestEnvironment = "sandbox"
)

// Valid indicates whether the value is a known member of the CreateProjectRequestEnvironment enum.
func (e CreateProjectRequestEnvironment) Valid() bool {
	switch e {
	case CreateProjectRequestEnvironmentProduction:
		return true
	case CreateProjectRequestEnvironmentSandbox:
		return true
	default:
		return false
	}
}

// Defines values for ProjectEnvironment.
const (
	ProjectEnvironmentProduction ProjectEnvironment = "production"
	ProjectEnvironmentSandbox    ProjectEnvironment = "sandbox"
)

// Valid indicates whether the value is a known member of the ProjectEnvironment enum.
func (e ProjectEnvironment) Valid() bool {
	switch e {
	case ProjectEnvironmentProduction:
		return true
	case ProjectEnvironmentSandbox:
		return true
	default:
		return false
	}
}

// Defines values for ProjectStatus.
const (
	ProjectStatusActive   ProjectStatus = "active"
	ProjectStatusDisabled ProjectStatus = "disabled"
)

// Valid indicates whether the value is a known member of the ProjectStatus enum.
func (e ProjectStatus) Valid() bool {
	switch e {
	case ProjectStatusActive:
		return true
	case ProjectStatusDisabled:
		return true
	default:
		return false
	}
}

// Defines values for ProjectUserStatus.
const (
	ProjectUserStatusActive   ProjectUserStatus = "active"
	ProjectUserStatusDisabled ProjectUserStatus = "disabled"
)

// Valid indicates whether the value is a known member of the ProjectUserStatus enum.
func (e ProjectUserStatus) Valid() bool {
	switch e {
	case ProjectUserStatusActive:
		return true
	case ProjectUserStatusDisabled:
		return true
	default:
		return false
	}
}

// Defines values for TenantMemberRole.
const (
	Owner TenantMemberRole = "owner"
)

// Valid indicates whether the value is a known member of the TenantMemberRole enum.
func (e TenantMemberRole) Valid() bool {
	switch e {
	case Owner:
		return true
	default:
		return false
	}
}

// Defines values for UpdateProjectRequestEnvironment.
const (
	Production UpdateProjectRequestEnvironment = "production"
	Sandbox    UpdateProjectRequestEnvironment = "sandbox"
)

// Valid indicates whether the value is a known member of the UpdateProjectRequestEnvironment enum.
func (e UpdateProjectRequestEnvironment) Valid() bool {
	switch e {
	case Production:
		return true
	case Sandbox:
		return true
	default:
		return false
	}
}

// Defines values for UpdateProjectRequestStatus.
const (
	UpdateProjectRequestStatusActive   UpdateProjectRequestStatus = "active"
	UpdateProjectRequestStatusDisabled UpdateProjectRequestStatus = "disabled"
)

// Valid indicates whether the value is a known member of the UpdateProjectRequestStatus enum.
func (e UpdateProjectRequestStatus) Valid() bool {
	switch e {
	case UpdateProjectRequestStatusActive:
		return true
	case UpdateProjectRequestStatusDisabled:
		return true
	default:
		return false
	}
}

// Defines values for UpdateProjectUserRequestStatus.
const (
	UpdateProjectUserRequestStatusActive   UpdateProjectUserRequestStatus = "active"
	UpdateProjectUserRequestStatusDisabled UpdateProjectUserRequestStatus = "disabled"
)

// Valid indicates whether the value is a known member of the UpdateProjectUserRequestStatus enum.
func (e UpdateProjectUserRequestStatus) Valid() bool {
	switch e {
	case UpdateProjectUserRequestStatusActive:
		return true
	case UpdateProjectUserRequestStatusDisabled:
		return true
	default:
		return false
	}
}

// ApiKey defines model for ApiKey.
type ApiKey struct {
	CreatedAt  Timestamp    `json:"created_at"`
	LastUsedAt *time.Time   `json:"last_used_at,omitempty"`
	Name       string       `json:"name"`
	Prefix     string       `json:"prefix"`
	RevokedAt  *time.Time   `json:"revoked_at,omitempty"`
	Status     ApiKeyStatus `json:"status"`
	Uid        Uuid         `json:"uid"`
}

// ApiKeyStatus defines model for ApiKey.Status.
type ApiKeyStatus string

// ApiKeySecret defines model for ApiKeySecret.
type ApiKeySecret struct {
	CreatedAt  Timestamp          `json:"created_at"`
	LastUsedAt *time.Time         `json:"last_used_at,omitempty"`
	Name       string             `json:"name"`
	Prefix     string             `json:"prefix"`
	RevokedAt  *time.Time         `json:"revoked_at,omitempty"`
	Secret     *string            `json:"secret,omitempty"`
	Status     ApiKeySecretStatus `json:"status"`
	Uid        Uuid               `json:"uid"`
}

// ApiKeySecretStatus defines model for ApiKeySecret.Status.
type ApiKeySecretStatus string

// AuditEvent defines model for AuditEvent.
type AuditEvent struct {
	Action     string                  `json:"action"`
	ActorType  AuditEventActorType     `json:"actor_type"`
	ActorUid   *openapi_types.UUID     `json:"actor_uid,omitempty"`
	CreatedAt  Timestamp               `json:"created_at"`
	Metadata   *map[string]interface{} `json:"metadata,omitempty"`
	TargetType *string                 `json:"target_type,omitempty"`
	TargetUid  *openapi_types.UUID     `json:"target_uid,omitempty"`
	Uid        Uuid                    `json:"uid"`
}

// AuditEventActorType defines model for AuditEvent.ActorType.
type AuditEventActorType string

// AuditPage defines model for AuditPage.
type AuditPage struct {
	Items      []AuditEvent `json:"items"`
	NextCursor *string      `json:"next_cursor,omitempty"`
}

// ConsoleSession defines model for ConsoleSession.
type ConsoleSession struct {
	ExpiresAt Timestamp    `json:"expires_at"`
	Member    TenantMember `json:"member"`
	Tenant    Tenant       `json:"tenant"`
}

// CreateOriginRequest defines model for CreateOriginRequest.
type CreateOriginRequest struct {
	Origin string `json:"origin"`
}

// CreateProjectRequest defines model for CreateProjectRequest.
type CreateProjectRequest struct {
	Environment   CreateProjectRequestEnvironment `json:"environment"`
	InitialOrigin string                          `json:"initial_origin"`
	Name          string                          `json:"name"`
	RpId          string                          `json:"rp_id"`
	RpName        string                          `json:"rp_name"`
}

// CreateProjectRequestEnvironment defines model for CreateProjectRequest.Environment.
type CreateProjectRequestEnvironment string

// CreateProjectUserRequest defines model for CreateProjectUserRequest.
type CreateProjectUserRequest struct {
	Email         openapi_types.Email `json:"email"`
	EmailVerified *bool               `json:"email_verified,omitempty"`
	Password      *string             `json:"password,omitempty"`
}

// ErrorEnvelope defines model for ErrorEnvelope.
type ErrorEnvelope struct {
	Error struct {
		Code      string                  `json:"code"`
		Details   *map[string]interface{} `json:"details,omitempty"`
		Message   string                  `json:"message"`
		RequestId string                  `json:"request_id"`
	} `json:"error"`
}

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Email    openapi_types.Email `json:"email"`
	Password string              `json:"password"`
}

// NameRequest defines model for NameRequest.
type NameRequest struct {
	Name string `json:"name"`
}

// AllowedOrigin defines model for Origin.
type AllowedOrigin struct {
	CreatedAt Timestamp `json:"created_at"`
	Origin    string    `json:"origin"`
	Uid       Uuid      `json:"uid"`
}

// Passkey defines model for Passkey.
type Passkey struct {
	CreatedAt Timestamp `json:"created_at"`
	Uid       Uuid      `json:"uid"`
}

// PasswordRequest defines model for PasswordRequest.
type PasswordRequest struct {
	Password string `json:"password"`
}

// Project defines model for Project.
type Project struct {
	ApiKeyCount int                `json:"api_key_count"`
	CreatedAt   Timestamp          `json:"created_at"`
	Environment ProjectEnvironment `json:"environment"`
	Name        string             `json:"name"`
	OriginCount int                `json:"origin_count"`
	Origins     []AllowedOrigin    `json:"origins"`
	RpId        string             `json:"rp_id"`
	RpIdLocked  bool               `json:"rp_id_locked"`
	RpName      string             `json:"rp_name"`
	Status      ProjectStatus      `json:"status"`
	Uid         Uuid               `json:"uid"`
	UserCount   int                `json:"user_count"`
}

// ProjectEnvironment defines model for Project.Environment.
type ProjectEnvironment string

// ProjectStatus defines model for Project.Status.
type ProjectStatus string

// ProjectPage defines model for ProjectPage.
type ProjectPage struct {
	Items      []Project `json:"items"`
	NextCursor *string   `json:"next_cursor,omitempty"`
}

// ProjectUser defines model for ProjectUser.
type ProjectUser struct {
	CreatedAt     Timestamp           `json:"created_at"`
	Email         openapi_types.Email `json:"email"`
	EmailVerified bool                `json:"email_verified"`
	PasskeyCount  int                 `json:"passkey_count"`
	Status        ProjectUserStatus   `json:"status"`
	Uid           Uuid                `json:"uid"`
}

// ProjectUserStatus defines model for ProjectUser.Status.
type ProjectUserStatus string

// ProjectUserPage defines model for ProjectUserPage.
type ProjectUserPage struct {
	Items      []ProjectUser `json:"items"`
	NextCursor *string       `json:"next_cursor,omitempty"`
}

// ProjectUserSession defines model for ProjectUserSession.
type ProjectUserSession struct {
	Active      bool        `json:"active"`
	ExpiresAt   Timestamp   `json:"expires_at"`
	ProjectUser ProjectUser `json:"project_user"`
}

// ProjectUserSessionSecret defines model for ProjectUserSessionSecret.
type ProjectUserSessionSecret struct {
	ExpiresAt        Timestamp   `json:"expires_at"`
	ProjectUser      ProjectUser `json:"project_user"`
	SessionReference *string     `json:"session_reference,omitempty"`
}

// RuntimePasswordRequest defines model for RuntimePasswordRequest.
type RuntimePasswordRequest = LoginRequest

// SessionReferenceRequest defines model for SessionReferenceRequest.
type SessionReferenceRequest struct {
	SessionReference *string `json:"session_reference,omitempty"`
}

// SignupRequest defines model for SignupRequest.
type SignupRequest struct {
	DisplayName string              `json:"display_name"`
	Email       openapi_types.Email `json:"email"`
	Password    string              `json:"password"`
	TenantName  string              `json:"tenant_name"`
}

// Tenant defines model for Tenant.
type Tenant struct {
	Name string `json:"name"`
	Slug string `json:"slug"`
	Uid  Uuid   `json:"uid"`
}

// TenantMember defines model for TenantMember.
type TenantMember struct {
	DisplayName string              `json:"display_name"`
	Email       openapi_types.Email `json:"email"`
	Role        TenantMemberRole    `json:"role"`
	Uid         Uuid                `json:"uid"`
}

// TenantMemberRole defines model for TenantMember.Role.
type TenantMemberRole string

// Timestamp defines model for Timestamp.
type Timestamp = time.Time

// UpdateProjectRequest defines model for UpdateProjectRequest.
type UpdateProjectRequest struct {
	Environment *UpdateProjectRequestEnvironment `json:"environment,omitempty"`
	Name        *string                          `json:"name,omitempty"`
	RpId        *string                          `json:"rp_id,omitempty"`
	RpName      *string                          `json:"rp_name,omitempty"`
	Status      *UpdateProjectRequestStatus      `json:"status,omitempty"`
}

// UpdateProjectRequestEnvironment defines model for UpdateProjectRequest.Environment.
type UpdateProjectRequestEnvironment string

// UpdateProjectRequestStatus defines model for UpdateProjectRequest.Status.
type UpdateProjectRequestStatus string

// UpdateProjectUserRequest defines model for UpdateProjectUserRequest.
type UpdateProjectUserRequest struct {
	Email         *openapi_types.Email            `json:"email,omitempty"`
	EmailVerified *bool                           `json:"email_verified,omitempty"`
	Status        *UpdateProjectUserRequestStatus `json:"status,omitempty"`
}

// UpdateProjectUserRequestStatus defines model for UpdateProjectUserRequest.Status.
type UpdateProjectUserRequestStatus string

// Uuid defines model for Uuid.
type Uuid = openapi_types.UUID

// WebAuthnFinishRequest defines model for WebAuthnFinishRequest.
type WebAuthnFinishRequest struct {
	CeremonyUid Uuid                   `json:"ceremony_uid"`
	Credential  map[string]interface{} `json:"credential"`
}

// WebAuthnOptions defines model for WebAuthnOptions.
type WebAuthnOptions struct {
	CeremonyUid Uuid                   `json:"ceremony_uid"`
	PublicKey   map[string]interface{} `json:"public_key"`
}

// CredentialUid defines model for CredentialUid.
type CredentialUid = Uuid

// Cursor defines model for Cursor.
type Cursor = string

// KeyUid defines model for KeyUid.
type KeyUid = Uuid

// Limit defines model for Limit.
type Limit = int

// Origin defines model for Origin.
type Origin = string

// OriginUid defines model for OriginUid.
type OriginUid = Uuid

// ProjectSession defines model for ProjectSession.
type ProjectSession = string

// ProjectUid defines model for ProjectUid.
type ProjectUid = Uuid

// UserUid defines model for UserUid.
type UserUid = Uuid

// Error defines model for Error.
type Error = ErrorEnvelope

// consoleSessionContextKey is the context key for consoleSession security scheme
type consoleSessionContextKey string

// projectApiKeyContextKey is the context key for projectApiKey security scheme
type projectApiKeyContextKey string

// ListTenantActivityParams defines parameters for ListTenantActivity.
type ListTenantActivityParams struct {
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit  *Limit  `form:"limit,omitempty" json:"limit,omitempty"`
}

// LoginParams defines parameters for Login.
type LoginParams struct {
	Origin *Origin `json:"Origin,omitempty"`
}

// LogoutParams defines parameters for Logout.
type LogoutParams struct {
	Origin *Origin `json:"Origin,omitempty"`
}

// SignupParams defines parameters for Signup.
type SignupParams struct {
	Origin *Origin `json:"Origin,omitempty"`
}

// ListProjectsParams defines parameters for ListProjects.
type ListProjectsParams struct {
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit  *Limit  `form:"limit,omitempty" json:"limit,omitempty"`
}

// CreateProjectParams defines parameters for CreateProject.
type CreateProjectParams struct {
	Origin *Origin `json:"Origin,omitempty"`
}

// UpdateProjectParams defines parameters for UpdateProject.
type UpdateProjectParams struct {
	Origin *Origin `json:"Origin,omitempty"`
}

// ListProjectActivityParams defines parameters for ListProjectActivity.
type ListProjectActivityParams struct {
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit  *Limit  `form:"limit,omitempty" json:"limit,omitempty"`
}

// CreateApiKeyParams defines parameters for CreateApiKey.
type CreateApiKeyParams struct {
	Origin *Origin `json:"Origin,omitempty"`
}

// RevokeApiKeyParams defines parameters for RevokeApiKey.
type RevokeApiKeyParams struct {
	Origin *Origin `json:"Origin,omitempty"`
}

// RenameApiKeyParams defines parameters for RenameApiKey.
type RenameApiKeyParams struct {
	Origin *Origin `json:"Origin,omitempty"`
}

// RotateApiKeyParams defines parameters for RotateApiKey.
type RotateApiKeyParams struct {
	Origin *Origin `json:"Origin,omitempty"`
}

// CreateOriginParams defines parameters for CreateOrigin.
type CreateOriginParams struct {
	Origin *Origin `json:"Origin,omitempty"`
}

// DeleteOriginParams defines parameters for DeleteOrigin.
type DeleteOriginParams struct {
	Origin *Origin `json:"Origin,omitempty"`
}

// BeginPasskeyAuthenticationJSONBody defines parameters for BeginPasskeyAuthentication.
type BeginPasskeyAuthenticationJSONBody struct {
	Email *openapi_types.Email `json:"email,omitempty"`
}

// BeginPasskeyRegistrationParams defines parameters for BeginPasskeyRegistration.
type BeginPasskeyRegistrationParams struct {
	XComplicatedAuthSession ProjectSession `json:"X-ComplicatedAuth-Session"`
}

// FinishPasskeyRegistrationParams defines parameters for FinishPasskeyRegistration.
type FinishPasskeyRegistrationParams struct {
	XComplicatedAuthSession ProjectSession `json:"X-ComplicatedAuth-Session"`
}

// ListProjectUsersParams defines parameters for ListProjectUsers.
type ListProjectUsersParams struct {
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit  *Limit  `form:"limit,omitempty" json:"limit,omitempty"`
}

// UpdateProjectUserParams defines parameters for UpdateProjectUser.
type UpdateProjectUserParams struct {
	Origin *Origin `json:"Origin,omitempty"`
}

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = LoginRequest

// SignupJSONRequestBody defines body for Signup for application/json ContentType.
type SignupJSONRequestBody = SignupRequest

// CreateProjectJSONRequestBody defines body for CreateProject for application/json ContentType.
type CreateProjectJSONRequestBody = CreateProjectRequest

// UpdateProjectJSONRequestBody defines body for UpdateProject for application/json ContentType.
type UpdateProjectJSONRequestBody = UpdateProjectRequest

// CreateApiKeyJSONRequestBody defines body for CreateApiKey for application/json ContentType.
type CreateApiKeyJSONRequestBody = NameRequest

// RenameApiKeyJSONRequestBody defines body for RenameApiKey for application/json ContentType.
type RenameApiKeyJSONRequestBody = NameRequest

// CreateOriginJSONRequestBody defines body for CreateOrigin for application/json ContentType.
type CreateOriginJSONRequestBody = CreateOriginRequest

// BeginPasskeyAuthenticationJSONRequestBody defines body for BeginPasskeyAuthentication for application/json ContentType.
type BeginPasskeyAuthenticationJSONRequestBody BeginPasskeyAuthenticationJSONBody

// FinishPasskeyAuthenticationJSONRequestBody defines body for FinishPasskeyAuthentication for application/json ContentType.
type FinishPasskeyAuthenticationJSONRequestBody = WebAuthnFinishRequest

// FinishPasskeyRegistrationJSONRequestBody defines body for FinishPasskeyRegistration for application/json ContentType.
type FinishPasskeyRegistrationJSONRequestBody = WebAuthnFinishRequest

// AuthenticateProjectUserPasswordJSONRequestBody defines body for AuthenticateProjectUserPassword for application/json ContentType.
type AuthenticateProjectUserPasswordJSONRequestBody = RuntimePasswordRequest

// IntrospectProjectUserSessionJSONRequestBody defines body for IntrospectProjectUserSession for application/json ContentType.
type IntrospectProjectUserSessionJSONRequestBody = SessionReferenceRequest

// RevokeProjectUserSessionJSONRequestBody defines body for RevokeProjectUserSession for application/json ContentType.
type RevokeProjectUserSessionJSONRequestBody = SessionReferenceRequest

// CreateProjectUserJSONRequestBody defines body for CreateProjectUser for application/json ContentType.
type CreateProjectUserJSONRequestBody = CreateProjectUserRequest

// UpdateProjectUserJSONRequestBody defines body for UpdateProjectUser for application/json ContentType.
type UpdateProjectUserJSONRequestBody = UpdateProjectUserRequest

// ReplaceProjectUserPasswordJSONRequestBody defines body for ReplaceProjectUserPassword for application/json ContentType.
type ReplaceProjectUserPasswordJSONRequestBody = PasswordRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /health/live)
	Live(w http.ResponseWriter, r *http.Request)

	// (GET /health/ready)
	Ready(w http.ResponseWriter, r *http.Request)

	// (GET /v1/activity)
	ListTenantActivity(w http.ResponseWriter, r *http.Request, params ListTenantActivityParams)

	// (POST /v1/console/auth/login)
	Login(w http.ResponseWriter, r *http.Request, params LoginParams)

	// (POST /v1/console/auth/logout)
	Logout(w http.ResponseWriter, r *http.Request, params LogoutParams)

	// (GET /v1/console/auth/session)
	GetConsoleSession(w http.ResponseWriter, r *http.Request)

	// (POST /v1/console/auth/signup)
	Signup(w http.ResponseWriter, r *http.Request, params SignupParams)

	// (GET /v1/projects)
	ListProjects(w http.ResponseWriter, r *http.Request, params ListProjectsParams)

	// (POST /v1/projects)
	CreateProject(w http.ResponseWriter, r *http.Request, params CreateProjectParams)

	// (GET /v1/projects/{project_uid})
	GetProject(w http.ResponseWriter, r *http.Request, projectUid ProjectUid)

	// (PATCH /v1/projects/{project_uid})
	UpdateProject(w http.ResponseWriter, r *http.Request, projectUid ProjectUid, params UpdateProjectParams)

	// (GET /v1/projects/{project_uid}/activity)
	ListProjectActivity(w http.ResponseWriter, r *http.Request, projectUid ProjectUid, params ListProjectActivityParams)

	// (GET /v1/projects/{project_uid}/api-keys)
	ListApiKeys(w http.ResponseWriter, r *http.Request, projectUid ProjectUid)

	// (POST /v1/projects/{project_uid}/api-keys)
	CreateApiKey(w http.ResponseWriter, r *http.Request, projectUid ProjectUid, params CreateApiKeyParams)

	// (DELETE /v1/projects/{project_uid}/api-keys/{key_uid})
	RevokeApiKey(w http.ResponseWriter, r *http.Request, projectUid ProjectUid, keyUid KeyUid, params RevokeApiKeyParams)

	// (PATCH /v1/projects/{project_uid}/api-keys/{key_uid})
	RenameApiKey(w http.ResponseWriter, r *http.Request, projectUid ProjectUid, keyUid KeyUid, params RenameApiKeyParams)

	// (POST /v1/projects/{project_uid}/api-keys/{key_uid}/rotate)
	RotateApiKey(w http.ResponseWriter, r *http.Request, projectUid ProjectUid, keyUid KeyUid, params RotateApiKeyParams)

	// (GET /v1/projects/{project_uid}/origins)
	ListOrigins(w http.ResponseWriter, r *http.Request, projectUid ProjectUid)

	// (POST /v1/projects/{project_uid}/origins)
	CreateOrigin(w http.ResponseWriter, r *http.Request, projectUid ProjectUid, params CreateOriginParams)

	// (DELETE /v1/projects/{project_uid}/origins/{origin_uid})
	DeleteOrigin(w http.ResponseWriter, r *http.Request, projectUid ProjectUid, originUid OriginUid, params DeleteOriginParams)

	// (POST /v1/projects/{project_uid}/runtime/passkeys/authentication/options)
	BeginPasskeyAuthentication(w http.ResponseWriter, r *http.Request, projectUid ProjectUid)

	// (POST /v1/projects/{project_uid}/runtime/passkeys/authentication/verify)
	FinishPasskeyAuthentication(w http.ResponseWriter, r *http.Request, projectUid ProjectUid)

	// (POST /v1/projects/{project_uid}/runtime/passkeys/registration/options)
	BeginPasskeyRegistration(w http.ResponseWriter, r *http.Request, projectUid ProjectUid, params BeginPasskeyRegistrationParams)

	// (POST /v1/projects/{project_uid}/runtime/passkeys/registration/verify)
	FinishPasskeyRegistration(w http.ResponseWriter, r *http.Request, projectUid ProjectUid, params FinishPasskeyRegistrationParams)

	// (POST /v1/projects/{project_uid}/runtime/password/authenticate)
	AuthenticateProjectUserPassword(w http.ResponseWriter, r *http.Request, projectUid ProjectUid)

	// (POST /v1/projects/{project_uid}/runtime/sessions/introspect)
	IntrospectProjectUserSession(w http.ResponseWriter, r *http.Request, projectUid ProjectUid)

	// (POST /v1/projects/{project_uid}/runtime/sessions/revoke)
	RevokeProjectUserSession(w http.ResponseWriter, r *http.Request, projectUid ProjectUid)

	// (GET /v1/projects/{project_uid}/users)
	ListProjectUsers(w http.ResponseWriter, r *http.Request, projectUid ProjectUid, params ListProjectUsersParams)

	// (POST /v1/projects/{project_uid}/users)
	CreateProjectUser(w http.ResponseWriter, r *http.Request, projectUid ProjectUid)

	// (GET /v1/projects/{project_uid}/users/{user_uid})
	GetProjectUser(w http.ResponseWriter, r *http.Request, projectUid ProjectUid, userUid UserUid)

	// (PATCH /v1/projects/{project_uid}/users/{user_uid})
	UpdateProjectUser(w http.ResponseWriter, r *http.Request, projectUid ProjectUid, userUid UserUid, params UpdateProjectUserParams)

	// (DELETE /v1/projects/{project_uid}/users/{user_uid}/passkeys/{credential_uid})
	DeletePasskey(w http.ResponseWriter, r *http.Request, projectUid ProjectUid, userUid UserUid, credentialUid CredentialUid)

	// (PUT /v1/projects/{project_uid}/users/{user_uid}/password)
	ReplaceProjectUserPassword(w http.ResponseWriter, r *http.Request, projectUid ProjectUid, userUid UserUid)

	// (POST /v1/projects/{project_uid}/users/{user_uid}/sessions/revoke)
	RevokeProjectUserSessions(w http.ResponseWriter, r *http.Request, projectUid ProjectUid, userUid UserUid)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// Live operation middleware
func (siw *ServerInterfaceWrapper) Live(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, ConsoleSessionScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Live(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Ready operation middleware
func (siw *ServerInterfaceWrapper) Ready(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, ConsoleSessionScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Ready(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListTenantActivity operation middleware
func (siw *ServerInterfaceWrapper) ListTenantActivity(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	ctx := r.Context()

	ctx = context.WithValue(ctx, ConsoleSessionScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListTenantActivityParams

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", r.URL.Query(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "cursor"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cursor", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListTenantActivity(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Login operation middleware
func (siw *ServerInterfaceWrapper) Login(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params LoginParams

	headers := r.Header

	// ------------- Optional header parameter "Origin" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Origin")]; found {
		var Origin Origin
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Origin", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Origin", valueList[0], &Origin, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: "uri"})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Origin", Err: err})
			return
		}

		params.Origin = &Origin

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Login(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Logout operation middleware
func (siw *ServerInterfaceWrapper) Logout(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	ctx := r.Context()

	ctx = context.WithValue(ctx, ConsoleSessionScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params LogoutParams

	headers := r.Header

	// ------------- Optional header parameter "Origin" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Origin")]; found {
		var Origin Origin
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Origin", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Origin", valueList[0], &Origin, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: "uri"})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Origin", Err: err})
			return
		}

		params.Origin = &Origin

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Logout(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetConsoleSession operation middleware
func (siw *ServerInterfaceWrapper) GetConsoleSession(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, ConsoleSessionScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetConsoleSession(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Signup operation middleware
func (siw *ServerInterfaceWrapper) Signup(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params SignupParams

	headers := r.Header

	// ------------- Optional header parameter "Origin" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Origin")]; found {
		var Origin Origin
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Origin", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Origin", valueList[0], &Origin, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: "uri"})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Origin", Err: err})
			return
		}

		params.Origin = &Origin

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Signup(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListProjects operation middleware
func (siw *ServerInterfaceWrapper) ListProjects(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	ctx := r.Context()

	ctx = context.WithValue(ctx, ConsoleSessionScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListProjectsParams

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", r.URL.Query(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "cursor"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cursor", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListProjects(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateProject operation middleware
func (siw *ServerInterfaceWrapper) CreateProject(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	ctx := r.Context()

	ctx = context.WithValue(ctx, ConsoleSessionScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params CreateProjectParams

	headers := r.Header

	// ------------- Optional header parameter "Origin" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Origin")]; found {
		var Origin Origin
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Origin", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Origin", valueList[0], &Origin, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: "uri"})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Origin", Err: err})
			return
		}

		params.Origin = &Origin

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateProject(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetProject operation middleware
func (siw *ServerInterfaceWrapper) GetProject(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "project_uid" -------------
	var projectUid ProjectUid

	err = runtime.BindStyledParameterWithOptions("simple", "project_uid", r.PathValue("project_uid"), &projectUid, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "project_uid", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, ConsoleSessionScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetProject(w, r, projectUid)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateProject operation middleware
func (siw *ServerInterfaceWrapper) UpdateProject(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "project_uid" -------------
	var projectUid ProjectUid

	err = runtime.BindStyledParameterWithOptions("simple", "project_uid", r.PathValue("project_uid"), &projectUid, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "project_uid", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, ConsoleSessionScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params UpdateProjectParams

	headers := r.Header

	// ------------- Optional header parameter "Origin" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Origin")]; found {
		var Origin Origin
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Origin", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Origin", valueList[0], &Origin, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: "uri"})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Origin", Err: err})
			return
		}

		params.Origin = &Origin

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateProject(w, r, projectUid, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListProjectActivity operation middleware
func (siw *ServerInterfaceWrapper) ListProjectActivity(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "project_uid" -------------
	var projectUid ProjectUid

	err = runtime.BindStyledParameterWithOptions("simple", "project_uid", r.PathValue("project_uid"), &projectUid, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "project_uid", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, ConsoleSessionScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListProjectActivityParams

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", r.URL.Query(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "cursor"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cursor", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListProjectActivity(w, r, projectUid, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListApiKeys operation middleware
func (siw *ServerInterfaceWrapper) ListApiKeys(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "project_uid" -------------
	var projectUid ProjectUid

	err = runtime.BindStyledParameterWithOptions("simple", "project_uid", r.PathValue("project_uid"), &projectUid, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "project_uid", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, ConsoleSessionScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListApiKeys(w, r, projectUid)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateApiKey operation middleware
func (siw *ServerInterfaceWrapper) CreateApiKey(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "project_uid" -------------
	var projectUid ProjectUid

	err = runtime.BindStyledParameterWithOptions("simple", "project_uid", r.PathValue("project_uid"), &projectUid, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "project_uid", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, ConsoleSessionScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params CreateApiKeyParams

	headers := r.Header

	// ------------- Optional header parameter "Origin" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Origin")]; found {
		var Origin Origin
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Origin", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Origin", valueList[0], &Origin, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: "uri"})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Origin", Err: err})
			return
		}

		params.Origin = &Origin

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateApiKey(w, r, projectUid, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RevokeApiKey operation middleware
func (siw *ServerInterfaceWrapper) RevokeApiKey(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "project_uid" -------------
	var projectUid ProjectUid

	err = runtime.BindStyledParameterWithOptions("simple", "project_uid", r.PathValue("project_uid"), &projectUid, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "project_uid", Err: err})
		return
	}

	// ------------- Path parameter "key_uid" -------------
	var keyUid KeyUid

	err = runtime.BindStyledParameterWithOptions("simple", "key_uid", r.PathValue("key_uid"), &keyUid, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "key_uid", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, ConsoleSessionScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params RevokeApiKeyParams

	headers := r.Header

	// ------------- Optional header parameter "Origin" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Origin")]; found {
		var Origin Origin
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Origin", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Origin", valueList[0], &Origin, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: "uri"})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Origin", Err: err})
			return
		}

		params.Origin = &Origin

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RevokeApiKey(w, r, projectUid, keyUid, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RenameApiKey operation middleware
func (siw *ServerInterfaceWrapper) RenameApiKey(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "project_uid" -------------
	var projectUid ProjectUid

	err = runtime.BindStyledParameterWithOptions("simple", "project_uid", r.PathValue("project_uid"), &projectUid, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "project_uid", Err: err})
		return
	}

	// ------------- Path parameter "key_uid" -------------
	var keyUid KeyUid

	err = runtime.BindStyledParameterWithOptions("simple", "key_uid", r.PathValue("key_uid"), &keyUid, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "key_uid", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, ConsoleSessionScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params RenameApiKeyParams

	headers := r.Header

	// ------------- Optional header parameter "Origin" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Origin")]; found {
		var Origin Origin
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Origin", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Origin", valueList[0], &Origin, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: "uri"})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Origin", Err: err})
			return
		}

		params.Origin = &Origin

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RenameApiKey(w, r, projectUid, keyUid, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RotateApiKey operation middleware
func (siw *ServerInterfaceWrapper) RotateApiKey(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "project_uid" -------------
	var projectUid ProjectUid

	err = runtime.BindStyledParameterWithOptions("simple", "project_uid", r.PathValue("project_uid"), &projectUid, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "project_uid", Err: err})
		return
	}

	// ------------- Path parameter "key_uid" -------------
	var keyUid KeyUid

	err = runtime.BindStyledParameterWithOptions("simple", "key_uid", r.PathValue("key_uid"), &keyUid, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "key_uid", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, ConsoleSessionScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params RotateApiKeyParams

	headers := r.Header

	// ------------- Optional header parameter "Origin" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Origin")]; found {
		var Origin Origin
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Origin", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Origin", valueList[0], &Origin, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: "uri"})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Origin", Err: err})
			return
		}

		params.Origin = &Origin

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RotateApiKey(w, r, projectUid, keyUid, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListOrigins operation middleware
func (siw *ServerInterfaceWrapper) ListOrigins(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "project_uid" -------------
	var projectUid ProjectUid

	err = runtime.BindStyledParameterWithOptions("simple", "project_uid", r.PathValue("project_uid"), &projectUid, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "project_uid", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, ConsoleSessionScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListOrigins(w, r, projectUid)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateOrigin operation middleware
func (siw *ServerInterfaceWrapper) CreateOrigin(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "project_uid" -------------
	var projectUid ProjectUid

	err = runtime.BindStyledParameterWithOptions("simple", "project_uid", r.PathValue("project_uid"), &projectUid, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "project_uid", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, ConsoleSessionScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params CreateOriginParams

	headers := r.Header

	// ------------- Optional header parameter "Origin" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Origin")]; found {
		var Origin Origin
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Origin", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Origin", valueList[0], &Origin, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: "uri"})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Origin", Err: err})
			return
		}

		params.Origin = &Origin

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateOrigin(w, r, projectUid, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteOrigin operation middleware
func (siw *ServerInterfaceWrapper) DeleteOrigin(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "project_uid" -------------
	var projectUid ProjectUid

	err = runtime.BindStyledParameterWithOptions("simple", "project_uid", r.PathValue("project_uid"), &projectUid, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "project_uid", Err: err})
		return
	}

	// ------------- Path parameter "origin_uid" -------------
	var originUid OriginUid

	err = runtime.BindStyledParameterWithOptions("simple", "origin_uid", r.PathValue("origin_uid"), &originUid, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "origin_uid", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, ConsoleSessionScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params DeleteOriginParams

	headers := r.Header

	// ------------- Optional header parameter "Origin" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Origin")]; found {
		var Origin Origin
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Origin", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Origin", valueList[0], &Origin, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: "uri"})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Origin", Err: err})
			return
		}

		params.Origin = &Origin

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteOrigin(w, r, projectUid, originUid, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// BeginPasskeyAuthentication operation middleware
func (siw *ServerInterfaceWrapper) BeginPasskeyAuthentication(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "project_uid" -------------
	var projectUid ProjectUid

	err = runtime.BindStyledParameterWithOptions("simple", "project_uid", r.PathValue("project_uid"), &projectUid, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "project_uid", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, ProjectApiKeyScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.BeginPasskeyAuthentication(w, r, projectUid)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// FinishPasskeyAuthentication operation middleware
func (siw *ServerInterfaceWrapper) FinishPasskeyAuthentication(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "project_uid" -------------
	var projectUid ProjectUid

	err = runtime.BindStyledParameterWithOptions("simple", "project_uid", r.PathValue("project_uid"), &projectUid, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "project_uid", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, ProjectApiKeyScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.FinishPasskeyAuthentication(w, r, projectUid)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// BeginPasskeyRegistration operation middleware
func (siw *ServerInterfaceWrapper) BeginPasskeyRegistration(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "project_uid" -------------
	var projectUid ProjectUid

	err = runtime.BindStyledParameterWithOptions("simple", "project_uid", r.PathValue("project_uid"), &projectUid, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "project_uid", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, ProjectApiKeyScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params BeginPasskeyRegistrationParams

	headers := r.Header

	// ------------- Required header parameter "X-ComplicatedAuth-Session" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-ComplicatedAuth-Session")]; found {
		var XComplicatedAuthSession ProjectSession
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-ComplicatedAuth-Session", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-ComplicatedAuth-Session", valueList[0], &XComplicatedAuthSession, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-ComplicatedAuth-Session", Err: err})
			return
		}

		params.XComplicatedAuthSession = XComplicatedAuthSession

	} else {
		err := fmt.Errorf("Header parameter X-ComplicatedAuth-Session is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "X-ComplicatedAuth-Session", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.BeginPasskeyRegistration(w, r, projectUid, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// FinishPasskeyRegistration operation middleware
func (siw *ServerInterfaceWrapper) FinishPasskeyRegistration(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "project_uid" -------------
	var projectUid ProjectUid

	err = runtime.BindStyledParameterWithOptions("simple", "project_uid", r.PathValue("project_uid"), &projectUid, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "project_uid", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, ProjectApiKeyScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params FinishPasskeyRegistrationParams

	headers := r.Header

	// ------------- Required header parameter "X-ComplicatedAuth-Session" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-ComplicatedAuth-Session")]; found {
		var XComplicatedAuthSession ProjectSession
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-ComplicatedAuth-Session", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-ComplicatedAuth-Session", valueList[0], &XComplicatedAuthSession, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-ComplicatedAuth-Session", Err: err})
			return
		}

		params.XComplicatedAuthSession = XComplicatedAuthSession

	} else {
		err := fmt.Errorf("Header parameter X-ComplicatedAuth-Session is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "X-ComplicatedAuth-Session", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.FinishPasskeyRegistration(w, r, projectUid, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AuthenticateProjectUserPassword operation middleware
func (siw *ServerInterfaceWrapper) AuthenticateProjectUserPassword(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "project_uid" -------------
	var projectUid ProjectUid

	err = runtime.BindStyledParameterWithOptions("simple", "project_uid", r.PathValue("project_uid"), &projectUid, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "project_uid", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, ProjectApiKeyScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AuthenticateProjectUserPassword(w, r, projectUid)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// IntrospectProjectUserSession operation middleware
func (siw *ServerInterfaceWrapper) IntrospectProjectUserSession(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "project_uid" -------------
	var projectUid ProjectUid

	err = runtime.BindStyledParameterWithOptions("simple", "project_uid", r.PathValue("project_uid"), &projectUid, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "project_uid", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, ProjectApiKeyScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.IntrospectProjectUserSession(w, r, projectUid)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RevokeProjectUserSession operation middleware
func (siw *ServerInterfaceWrapper) RevokeProjectUserSession(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "project_uid" -------------
	var projectUid ProjectUid

	err = runtime.BindStyledParameterWithOptions("simple", "project_uid", r.PathValue("project_uid"), &projectUid, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "project_uid", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, ProjectApiKeyScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RevokeProjectUserSession(w, r, projectUid)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListProjectUsers operation middleware
func (siw *ServerInterfaceWrapper) ListProjectUsers(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "project_uid" -------------
	var projectUid ProjectUid

	err = runtime.BindStyledParameterWithOptions("simple", "project_uid", r.PathValue("project_uid"), &projectUid, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "project_uid", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, ConsoleSessionScopes, []string{})

	ctx = context.WithValue(ctx, ProjectApiKeyScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListProjectUsersParams

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", r.URL.Query(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "cursor"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cursor", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListProjectUsers(w, r, projectUid, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateProjectUser operation middleware
func (siw *ServerInterfaceWrapper) CreateProjectUser(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "project_uid" -------------
	var projectUid ProjectUid

	err = runtime.BindStyledParameterWithOptions("simple", "project_uid", r.PathValue("project_uid"), &projectUid, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "project_uid", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, ConsoleSessionScopes, []string{})

	ctx = context.WithValue(ctx, ProjectApiKeyScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateProjectUser(w, r, projectUid)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetProjectUser operation middleware
func (siw *ServerInterfaceWrapper) GetProjectUser(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "project_uid" -------------
	var projectUid ProjectUid

	err = runtime.BindStyledParameterWithOptions("simple", "project_uid", r.PathValue("project_uid"), &projectUid, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "project_uid", Err: err})
		return
	}

	// ------------- Path parameter "user_uid" -------------
	var userUid UserUid

	err = runtime.BindStyledParameterWithOptions("simple", "user_uid", r.PathValue("user_uid"), &userUid, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "user_uid", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, ConsoleSessionScopes, []string{})

	ctx = context.WithValue(ctx, ProjectApiKeyScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetProjectUser(w, r, projectUid, userUid)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateProjectUser operation middleware
func (siw *ServerInterfaceWrapper) UpdateProjectUser(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "project_uid" -------------
	var projectUid ProjectUid

	err = runtime.BindStyledParameterWithOptions("simple", "project_uid", r.PathValue("project_uid"), &projectUid, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "project_uid", Err: err})
		return
	}

	// ------------- Path parameter "user_uid" -------------
	var userUid UserUid

	err = runtime.BindStyledParameterWithOptions("simple", "user_uid", r.PathValue("user_uid"), &userUid, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "user_uid", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, ConsoleSessionScopes, []string{})

	ctx = context.WithValue(ctx, ProjectApiKeyScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params UpdateProjectUserParams

	headers := r.Header

	// ------------- Optional header parameter "Origin" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Origin")]; found {
		var Origin Origin
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Origin", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Origin", valueList[0], &Origin, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: "uri"})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Origin", Err: err})
			return
		}

		params.Origin = &Origin

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateProjectUser(w, r, projectUid, userUid, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeletePasskey operation middleware
func (siw *ServerInterfaceWrapper) DeletePasskey(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "project_uid" -------------
	var projectUid ProjectUid

	err = runtime.BindStyledParameterWithOptions("simple", "project_uid", r.PathValue("project_uid"), &projectUid, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "project_uid", Err: err})
		return
	}

	// ------------- Path parameter "user_uid" -------------
	var userUid UserUid

	err = runtime.BindStyledParameterWithOptions("simple", "user_uid", r.PathValue("user_uid"), &userUid, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "user_uid", Err: err})
		return
	}

	// ------------- Path parameter "credential_uid" -------------
	var credentialUid CredentialUid

	err = runtime.BindStyledParameterWithOptions("simple", "credential_uid", r.PathValue("credential_uid"), &credentialUid, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "credential_uid", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, ConsoleSessionScopes, []string{})

	ctx = context.WithValue(ctx, ProjectApiKeyScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeletePasskey(w, r, projectUid, userUid, credentialUid)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ReplaceProjectUserPassword operation middleware
func (siw *ServerInterfaceWrapper) ReplaceProjectUserPassword(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "project_uid" -------------
	var projectUid ProjectUid

	err = runtime.BindStyledParameterWithOptions("simple", "project_uid", r.PathValue("project_uid"), &projectUid, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "project_uid", Err: err})
		return
	}

	// ------------- Path parameter "user_uid" -------------
	var userUid UserUid

	err = runtime.BindStyledParameterWithOptions("simple", "user_uid", r.PathValue("user_uid"), &userUid, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "user_uid", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, ConsoleSessionScopes, []string{})

	ctx = context.WithValue(ctx, ProjectApiKeyScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ReplaceProjectUserPassword(w, r, projectUid, userUid)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RevokeProjectUserSessions operation middleware
func (siw *ServerInterfaceWrapper) RevokeProjectUserSessions(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "project_uid" -------------
	var projectUid ProjectUid

	err = runtime.BindStyledParameterWithOptions("simple", "project_uid", r.PathValue("project_uid"), &projectUid, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "project_uid", Err: err})
		return
	}

	// ------------- Path parameter "user_uid" -------------
	var userUid UserUid

	err = runtime.BindStyledParameterWithOptions("simple", "user_uid", r.PathValue("user_uid"), &userUid, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "user_uid", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, ConsoleSessionScopes, []string{})

	ctx = context.WithValue(ctx, ProjectApiKeyScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RevokeProjectUserSessions(w, r, projectUid, userUid)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/health/live", wrapper.Live)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/health/ready", wrapper.Ready)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/activity", wrapper.ListTenantActivity)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/console/auth/login", wrapper.Login)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/console/auth/logout", wrapper.Logout)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/console/auth/session", wrapper.GetConsoleSession)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/console/auth/signup", wrapper.Signup)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/projects", wrapper.ListProjects)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/projects", wrapper.CreateProject)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/projects/{project_uid}", wrapper.GetProject)
	m.HandleFunc(http.MethodPatch+" "+options.BaseURL+"/v1/projects/{project_uid}", wrapper.UpdateProject)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/projects/{project_uid}/activity", wrapper.ListProjectActivity)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/projects/{project_uid}/api-keys", wrapper.ListApiKeys)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/projects/{project_uid}/api-keys", wrapper.CreateApiKey)
	m.HandleFunc(http.MethodDelete+" "+options.BaseURL+"/v1/projects/{project_uid}/api-keys/{key_uid}", wrapper.RevokeApiKey)
	m.HandleFunc(http.MethodPatch+" "+options.BaseURL+"/v1/projects/{project_uid}/api-keys/{key_uid}", wrapper.RenameApiKey)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/projects/{project_uid}/api-keys/{key_uid}/rotate", wrapper.RotateApiKey)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/projects/{project_uid}/origins", wrapper.ListOrigins)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/projects/{project_uid}/origins", wrapper.CreateOrigin)
	m.HandleFunc(http.MethodDelete+" "+options.BaseURL+"/v1/projects/{project_uid}/origins/{origin_uid}", wrapper.DeleteOrigin)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/projects/{project_uid}/runtime/passkeys/authentication/options", wrapper.BeginPasskeyAuthentication)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/projects/{project_uid}/runtime/passkeys/authentication/verify", wrapper.FinishPasskeyAuthentication)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/projects/{project_uid}/runtime/passkeys/registration/options", wrapper.BeginPasskeyRegistration)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/projects/{project_uid}/runtime/passkeys/registration/verify", wrapper.FinishPasskeyRegistration)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/projects/{project_uid}/runtime/password/authenticate", wrapper.AuthenticateProjectUserPassword)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/projects/{project_uid}/runtime/sessions/introspect", wrapper.IntrospectProjectUserSession)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/projects/{project_uid}/runtime/sessions/revoke", wrapper.RevokeProjectUserSession)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/projects/{project_uid}/users", wrapper.ListProjectUsers)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/projects/{project_uid}/users", wrapper.CreateProjectUser)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/projects/{project_uid}/users/{user_uid}", wrapper.GetProjectUser)
	m.HandleFunc(http.MethodPatch+" "+options.BaseURL+"/v1/projects/{project_uid}/users/{user_uid}", wrapper.UpdateProjectUser)
	m.HandleFunc(http.MethodDelete+" "+options.BaseURL+"/v1/projects/{project_uid}/users/{user_uid}/passkeys/{credential_uid}", wrapper.DeletePasskey)
	m.HandleFunc(http.MethodPut+" "+options.BaseURL+"/v1/projects/{project_uid}/users/{user_uid}/password", wrapper.ReplaceProjectUserPassword)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/projects/{project_uid}/users/{user_uid}/sessions/revoke", wrapper.RevokeProjectUserSessions)

	return m
}
